apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: dionysus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dionysus
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: dionysus-0.1.0
  name: dionysus-metrics
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: dionysus
    app.kubernetes.io/name: dionysus
  type: ClusterIP
