apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: dionysus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dionysus
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: dionysus-0.1.0
  name: dionysus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: dionysus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dionysus
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: dionysus-0.1.0
  name: dionysus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dionysus
      app.kubernetes.io/name: dionysus
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dionysus
        app.kubernetes.io/name: dionysus
    spec:
      containers:
        - env:
            - name: METRICS_PORT
              value: '8080'
          image: ghcr.io/olivecasazza/dionysus:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: probe
          name: dionysus
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: probe
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
        - name: ghcr-pull
      serviceAccountName: dionysus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: dionysus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dionysus
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: dionysus-0.1.0
  name: dionysus-metrics
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: dionysus
    app.kubernetes.io/name: dionysus
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: dionysus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dionysus
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: dionysus-0.1.0
  name: dionysus-role
rules:
  - apiGroups:
      - games.dionysus.io
    resources:
      - hostedgames
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - games.dionysus.io
    resources:
      - hostedgames/status
      - hostedgames/finalizers
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - services
      - persistentvolumeclaims
      - pods
      - pods/log
      - pods/exec
      - events
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: dionysus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dionysus
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: dionysus-0.1.0
  name: dionysus-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dionysus-role
subjects:
  - kind: ServiceAccount
    name: dionysus
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: dionysus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dionysus
    app.kubernetes.io/version: 0.1.0
    helm.sh/chart: dionysus-0.1.0
  name: dionysus
spec:
  endpoints:
    - interval: 15s
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: dionysus
      app.kubernetes.io/name: dionysus
